- src:     https://github.com/ElaoInfra/ansible-role-motd
  name:    elao.motd
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-timezone
  name:    elao.timezone
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-env
  name:    elao.env
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-apt
  name:    elao.apt
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-ssh
  name:    elao.ssh
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-git
  name:    elao.git
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-zsh
  name:    elao.zsh
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-ohmyzsh
  name:    elao.ohmyzsh
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-vim
  name:    elao.vim
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-curl
  name:    elao.curl
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-acl
  name:    elao.acl
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-files
  name:    elao.files
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-make
  name:    elao.make
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-php
  name:    elao.php
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-composer
  name:    elao.composer
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-nginx
  name:    elao.nginx
  version: origin/1.0

- src:     https://github.com/ElaoInfra/ansible-role-mysql
  name:    elao.mysql
  version: origin/1.0
